/**
 * Network config generator — produces vendor CLI templates from VLSM allocations.
 */

/**
 * Generate a Cisco IOS/IOS-XE interface + OSPF config.
 * @param {Array} allocations - VLSM allocations
 * @param {Object} [options]
 * @returns {string}
 */
export function generateCisco(allocations, options = {}) {
  const { hostname = 'ROUTER-1', ospfProcess = 1 } = options;
  const lines = [];

  lines.push(`! ── Cisco IOS — Generated by Net Architect ──`);
  lines.push(`hostname ${hostname}`);
  lines.push('!');
  lines.push('ip routing');
  lines.push('!');

  allocations.filter(a => !a.error).forEach((alloc, i) => {
    const ifName = `GigabitEthernet0/${i}`;
    lines.push(`interface ${ifName}`);
    lines.push(` description ${alloc.name}`);
    lines.push(` ip address ${alloc.firstHost} ${alloc.subnetMask}`);
    lines.push(' no shutdown');
    lines.push('!');
  });

  lines.push(`router ospf ${ospfProcess}`);
  lines.push(` router-id 1.1.1.1`);
  allocations.filter(a => !a.error).forEach(alloc => {
    lines.push(` network ${alloc.network} ${invertMask(alloc.subnetMask)} area 0`);
  });
  lines.push('!');
  lines.push('end');

  return lines.join('\n');
}

/**
 * Generate a Juniper Junos configuration stanza.
 * @param {Array} allocations
 * @param {Object} [options]
 * @returns {string}
 */
export function generateJuniper(allocations, options = {}) {
  const { hostname = 'router-1' } = options;
  const lines = [];

  lines.push(`# ── Juniper Junos — Generated by Net Architect ──`);
  lines.push(`system {`);
  lines.push(`    host-name ${hostname};`);
  lines.push(`}`);
  lines.push('interfaces {');

  allocations.filter(a => !a.error).forEach((alloc, i) => {
    lines.push(`    ge-0/0/${i} {`);
    lines.push(`        description "${alloc.name}";`);
    lines.push(`        unit 0 {`);
    lines.push(`            family inet {`);
    lines.push(`                address ${alloc.firstHost}/${alloc.prefix};`);
    lines.push(`            }`);
    lines.push(`        }`);
    lines.push(`    }`);
  });

  lines.push('}');
  lines.push('protocols {');
  lines.push('    ospf {');
  lines.push('        area 0.0.0.0 {');
  allocations.filter(a => !a.error).forEach((alloc, i) => {
    lines.push(`            interface ge-0/0/${i}.0;`);
  });
  lines.push('        }');
  lines.push('    }');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate a Huawei VRP configuration.
 * @param {Array} allocations
 * @param {Object} [options]
 * @returns {string}
 */
export function generateHuawei(allocations, options = {}) {
  const { hostname = 'Router1' } = options;
  const lines = [];

  lines.push(`# ── Huawei VRP — Generated by Net Architect ──`);
  lines.push(`sysname ${hostname}`);
  lines.push('#');

  allocations.filter(a => !a.error).forEach((alloc, i) => {
    lines.push(`interface GigabitEthernet0/0/${i}`);
    lines.push(` description ${alloc.name}`);
    lines.push(` ip address ${alloc.firstHost} ${alloc.subnetMask}`);
    lines.push('#');
  });

  lines.push('ospf 1 router-id 1.1.1.1');
  lines.push(' area 0.0.0.0');
  allocations.filter(a => !a.error).forEach(alloc => {
    lines.push(`  network ${alloc.network} ${invertMask(alloc.subnetMask)}`);
  });
  lines.push('#');
  lines.push('return');

  return lines.join('\n');
}

/**
 * Invert a subnet mask to produce a wildcard mask.
 * @param {string} mask - e.g. "255.255.255.0"
 * @returns {string} - e.g. "0.0.0.255"
 */
function invertMask(mask) {
  return mask.split('.').map(o => 255 - parseInt(o, 10)).join('.');
}
